name: Pull Request Template

description: |
  This template provides a structure for creating pull requests related to a csit_labs

# Define the sections of the pull request template
body:
  - type: markdown
    attributes:
      value: |
        ## Changes

        Describe the changes you are proposing in this pull request.

  - type: input
    id: title
    attributes:
      label: Title
      description: A short summary of the changes made.
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: Description
      description: |
        A detailed description of the changes made, including any relevant context or background information.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Database Changes

        If you made changes to the database schema or data, describe them here.

  - type: markdown
    attributes:
      value: |
        ## Testing

        Explain how the changes have been tested.

  - type: input
    id: test_plan
    attributes:
      label: Test Plan
      description: |
        Describe the testing that has been done to ensure the changes work as expected.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Review

        Explain what kind of feedback you are looking for.

  - type: input
    id: additional_feedback
    attributes:
      label: Additional Feedback
      description: |
        Provide any additional information that would be helpful to the reviewer(s).
